### ISSUE TITLE
trying to download the data gives access denied

### ISSUE THREAD

**Issue by skeydan** [Akanni96/TRUNET#3]
Hi,

your paper looks super interesting, and I'd like to see if I can port the model to R :-)

However, I get access denied when trying to download the data. Could you please check?

Thanks!

**Comment by Akanni96** [comment]
Hi, 
Thank you for the interest in the paper :)
I've looked into this problem and it appears to be an issue related to using Google Drive to share files with a compressed file extension such as .rar/.zip/.7 . The solution is as below.

**Problem**: 
- When you try to download a file with .rar extension from google drive and you get access denied error. 

**Solution**: 
- you can fix the error by opening a new private/incognito window.
- Copy the url of the file and paste that url in new private window. 
- Hit enter the file will automatically start to download.

Please tell me if this worked for you. In the meantime, I will look for a proper fix or consider using a different service to host the data.

**Comment by skeydan** [comment]
Hi, thanks a lot for the quick answer! :-)

In fact I was just going to update the issue. I tried downloading with Chrome and that did in fact work... (normally I use Brave, and there I still get the access denied error)

So for me this is fixed, but it might be useful for others to know :-)

**Comment by Akanni96** [comment]
Hi, thanks for providing shining some more light on the issue. 

I'll include the informations about the complications of Brave browser. 
I'll close this issue now.
